### ISSUE TITLE
hostapd mana light

### ISSUE THREAD

**Issue by hASVAN** [adde88/openwrt-useful-tools#1]
Soo im trying to install hostapd mana light but iget this error

root@OpenWrt:~# opkg install hostapd-mana-light_2.6-3_ar71xx.ipk
Installing hostapd-mana-light (2.6-3) to root...
Configuring hostapd-mana-light.
//usr/lib/opkg/info/hostapd-mana-light.postinst: line 4: default_postinst: not found
Collected errors:
 * pkg_run_script: package "hostapd-mana-light" postinst script returned status 127.
 * opkg_configure: hostapd-mana-light.postinst returned 127.

**Comment by adde88** [comment]
That's the same "error message" your're getting, when you tried installing asleap.
opkg is just whining about the IPK missing a postinst script, which it doesn't need.
So ANY error messages regarding ` default_postinst: not found` can safely be ignored.

I also need to add that the IPK you're trying to install is compiled with [this](https://archive.openwrt.org/chaos_calmer/15.05/ar71xx/generic/) SDK. So i cannot guarantee that it will work for your device.
After installing, test it by trying to run: hostapd-mana in your terminal.
